/**
 * Single source of truth for identity, links and navigation.
 *
 * Everything here comes from Niraj's own resume, LinkedIn export, financial
 * model or academic project files. Nothing is inferred or invented.
 *
 * To change the LinkedIn URL, edit `links.linkedin` below. It is referenced
 * from the header, hero, contact section and resume page.
 */
export const profile = {
  name: 'Niraj Chaudhari',
  monogram: 'NC',
  location: 'Pune, India',

  /** Roles to surface directly under the name. */
  targetRoles: [
    'Financial Analysis',
    'Corporate Finance',
    'FP&A',
    'Financial Modelling & Valuation',
    'Credit Risk Analysis',
  ],

  headline: 'MBA Finance | Financial Analysis | Modelling & Valuation',

  positioning:
    'MBA Finance candidate at MIT World Peace University, building financial models from published ' +
    'statements and company filings.',

  intro:
    'My work starts with a real business: rebuilding its financials from the statements, forecasting ' +
    'the drivers behind them, and reporting what the numbers support. That has meant a fully integrated ' +
    'three-statement model and DCF for Varun Beverages, a five-year working capital decomposition for ' +
    'Jubilant Foodworks, and credit risk modelling on borrower data at Datamind Labs. The quantitative ' +
    'foundation comes from IIT Madras and Great Learning; the finance training is what I am pursuing now.',

  /** Tighter variant used on the print resume, where space is the constraint. */
  resumeSummary:
    'MBA Finance candidate at MIT-WPU (expected July 2027, CGPA 8.31) with a data science foundation from ' +
    'IIT Madras and Great Learning. Builds fully linked financial models from published statements, covering ' +
    'three-statement forecasting, DCF and relative valuation, and working capital analysis, and applies Python ' +
    'and Power BI to credit risk and performance analysis. Seeking a financial analysis, corporate finance, ' +
    'FP&A or credit risk analyst role.',

  links: {
    // LinkedIn public profile URL from the most recent profile export.
    // The older resume PDF lists a legacy vanity URL. Verify before publishing.
    linkedin: 'https://www.linkedin.com/in/niraj-chaudharii',
    email: 'nirajchaudhari170503@gmail.com',
    phone: '+91-8767281554',
    // The downloadable one-page CV, generated by scripts/resume-one-page.html.
    resumePdf: '/Niraj-Chaudhari-Resume.pdf',
  },

  /**
   * Portrait for the About section.
   *
   * To publish a photo: save it as `public/portrait.jpg` (portrait crop, 4:5,
   * around 800x1000px, under 200KB) and it appears automatically. Until the
   * file exists the frame renders a designed title plate instead, so the
   * layout never shows a broken image.
   */
  photo: {
    src: '/portrait.jpg',
    alt: 'Portrait of Niraj Chaudhari',
  },
}

export const nav = [
  { label: 'About', to: '/#about' },
  { label: 'Projects', to: '/#projects' },
  { label: 'Experience', to: '/#experience' },
  { label: 'Education', to: '/#education' },
  { label: 'Certificates', to: '/#certificates' },
  { label: 'Skills', to: '/#skills' },
  { label: 'Contact', to: '/#contact' },
]
